TrajectoryPlannerROS:
  max_vel_x: 1.5
  min_vel_x: 0
  max_vel_theta: 3.5
  min_vel_theta: -3.5
  min_in_place_vel_theta: 1.0
  escape_vel: -1.5

  acc_lim_theta: 2.0
  acc_lim_x: 0.5
  acc_lim_y: 1.0

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.25

  controller_frequency: 5.0
