global_frame: map
robot_base_frame: base_footprint
always_send_full_costmap: true


transform_tolerance: 1.0
footprint: [[0.7, -0.7], [0.7, 0.7], [-0.7, 0.7], [-0.7, -0.7]]
map_type: costmap

inflation_layer:
  inflation_radius: 10.0
  cost_scaling_factor: 10.0

obstacle_layer:
  obstacle_range: 2.0
  raytrace_range: 5.0
  #max_obstacle_height: 1.7
  #origin_z: 0
  #z_resolution: 0.5
  #z_voxels: 2
  observation_sources: scan_laser 
  scan_laser: 
    sensor_frame: laser
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true

rgbd_obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
#  publish_voxel_map: True
  observation_sources: front_rgbd_to_scan
  front_rgbd_to_scan:
    data_type: PointCloud2
    topic: /camera/depth/points
    marking: True
    clearing: True
    voxel_filter: true




