local_costmap:
  global_frame: odom
#  global_frame: /odom_combined
  robot_base_frame: base_footprint
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 25.0 
  height: 25.0
  origin_x: -12.5
  origin_y: -12.5 
  resolution: 0.1
#  footprint_padding: 0.0
#  inflation_radius: 5.0

  
  
  plugins:
    -
      name: rgbd_obstacle_layer
      type: "costmap_2d::VoxelLayer"
    


