joint1_position_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_right_top_wheel
joint2_position_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_left_top_wheel
joint3_position_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_left_bottom_wheel
joint4_position_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_right_bottom_wheel

vast_robot:
  type: summit_xl_controller/SummitXLController
  joint:
    front_right_wheel_joint:
      name: joint_right_top_wheel
      max_speed: 27.27 # rad/s
    front_left_wheel_joint:
      name: joint_left_top_wheel
      max_speed: 27.27 # rad/s
    back_right_wheel_joint:
      name: joint_right_bottom_wheel
      max_speed: 27.27 # rad/s
    back_left_wheel_joint:
      name: joint_left_bottom_wheel
      max_speed: 27.27 # rad/s
  linear_speed_limit: 1.5 # m/s
  linear_acceleration_limit: 3 # m/s^2
  angular_speed_limit: 3 # rad/s
  angular_acceleration_limit: 3 # rad/s^2
  odom_frame: odom
  robot_base_frame: base_footprint
  odom_broadcast_tf: true
  odom_topic: 'odom'
  wheel_base: 0.458
  track_width: 0.462
  wheel_diameter: 0.4
  cmd_watchdog_duration: 0.2
  imu_watchdog_duration: 0.1
  # imu_topic: imu/data
  odom_publish_frequency: 100
  cmd_vel        : 'cmd_vel'
  kinematic_mode : 'omni'
  motion_odometry: true
  in_motion_timer: 2.0

joint_state_controller:
  type: joint_state_controller/JointStateController 
  publish_rate: 50.0



