vast_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_right_top_wheel
    pid: {p: 10, i: 0.0, d: 1}
  joint2_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_left_top_wheel
    pid: {p: 10, i: 0.0, d: 1}
  joint3_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_left_bottom_wheel
    pid: {p: 10, i: 0.0, d: 1}
  joint4_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_right_bottom_wheel
    pid: {p: 10, i: 0.0, d: 1}

